/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.guessinggame;

import java.awt.Dimension;

/**
 *
 * @author ivan
 */
public class GuessingGame extends javax.swing.JFrame {

    private int theNumber=(int)(Math.random()* 101);
    private int triesLeft=10;
// the number we are trying to guess
    public void checkGuess(){
        // method or function to check too high or too low
        //get the user's guess
        String guessText = txtGuess.getText();
        String message = "";
        
        try{           
        
        //checking the user's Guess
        int guess=Integer.parseInt(guessText);
        
        //count this as one try
        triesLeft--;
        
        //too high
        if (guess > theNumber){
            message=guess + " was too HIGH.";
            message += "You have " + triesLeft + " tries left.";
            lblOutput.setText(message);
        }
        else if (guess < theNumber){
            message=guess + " was too LOW.";
            message += "You have " + triesLeft + " tries left.";
            lblOutput.setText(message);
        }
        else{
            message=guess + " was right. You WIN!,";
            int counter =10-triesLeft;
            message += " with " + counter + " tries.";
            lblOutput.setText(message);
            newGame();
        }
        if(triesLeft<= 0){
            
            javax.swing.JOptionPane.showConfirmDialog(null, "Sorry, you  ran out of tries. The number was: " + theNumber + ". Play again?");
            newGame();
        }
    }
        catch(Exception e){
            lblOutput.setText("Enter a whole number between 1 & 100.");
        }
        finally{
        txtGuess.requestFocus();
        txtGuess.selectAll();
        }
    }
    public void newGame(){
        //create a new random number between 1 and 100
        theNumber=(int)(Math.random()* 101);
        triesLeft=10;
        
    }
    /**
     * Creates new form GuessingGame
     */
    public GuessingGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIntroducing = new javax.swing.JLabel();
        lblGuessaNumber = new javax.swing.JLabel();
        txtGuess = new javax.swing.JTextField();
        btnGuess = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(3000, 3000));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(36, 26, 41));
        jPanel1.setMaximumSize(new java.awt.Dimension(32000, 32000));

        lblIntroducing.setBackground(new java.awt.Color(230, 225, 225));
        lblIntroducing.setFont(new java.awt.Font("Chandas", 1, 24)); // NOI18N
        lblIntroducing.setForeground(new java.awt.Color(163, 173, 239));
        lblIntroducing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIntroducing.setText("Lic. Ivan Garcia's Hi-Lo Guessing Game");

        lblGuessaNumber.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        lblGuessaNumber.setForeground(new java.awt.Color(243, 239, 249));
        lblGuessaNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGuessaNumber.setText("Guess a number between 1 & 100");

        txtGuess.setFont(new java.awt.Font("Chandas", 0, 48)); // NOI18N
        txtGuess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuessActionPerformed(evt);
            }
        });

        btnGuess.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        btnGuess.setText("Guess");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        lblOutput.setBackground(java.awt.Color.black);
        lblOutput.setFont(new java.awt.Font("Chandas", 1, 18)); // NOI18N
        lblOutput.setForeground(java.awt.Color.lightGray);
        lblOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutput.setText("Enter a number above and click Guess, you have 10 Tries");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOutput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGuessaNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblIntroducing, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIntroducing)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGuessaNumber)
                    .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuess)
                .addGap(46, 46, 46)
                .addComponent(lblOutput)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        // TODO add your handling code here:
        checkGuess();

    }//GEN-LAST:event_btnGuessActionPerformed

    private void txtGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuessActionPerformed
        // TODO add your handling code here:
        checkGuess();
    }//GEN-LAST:event_txtGuessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        GuessingGame theGame = new GuessingGame();
        theGame.newGame();
        theGame.setSize(new Dimension(430,330));
        theGame.setVisible(true);
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGuessaNumber;
    private javax.swing.JLabel lblIntroducing;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JTextField txtGuess;
    // End of variables declaration//GEN-END:variables
}
